secrets:
  mysql_root_password:
    file: /etc/light/crud_db/mysql_root_password
  mysql_database:
    file: /etc/light/crud_db/mysql_database
  mysql_user:
    file: /etc/light/crud_db/mysql_user
  mysql_password:
    file: /etc/light/crud_db/mysql_password

services:
  crud_db: 
    secrets:
    - mysql_root_password
    - mysql_database
    - mysql_user
    - mysql_password
    environment:
      MYSQL_ROOT_PASSWORD: /run/secrets/mysql_root_password
      MYSQL_DATABASE: /run/secrets/mysql_database
      MYSQL_USER: /run/secrets/mysql_user
      MYSQL_PASSWORD: /run/secrets/mysql_password
    volumes:
      - /var/lib/dbs/crud:/var/lib/mysql 
      
  api:
    secrets:
    - mysql_database
    - mysql_user
    - mysql_password
    environment:
      NODE_ENV: production
      DB_HOST: crud_db
      MYSQL_USER: /run/secrets/mysql_user
      MYSQL_DATABASE: /run/secrets/mysql_database
      MYSQL_PASSWORD: /run/secrets/mysql_password
      CHOKIDAR_USEPOLLING: false
    labels:
      # Domain
      - "traefik.http.routers.crudapi.rule=Host(`crud.api.webnunez.com`)"
      #Certresolver
      - "traefik.http.routers.crudapi.tls.certresolver=prodcertresolver"

  client:
    environment:
      WATCHPACK_POLLING: false
    command: bash -c "
      npm install
      && mkdir -p node_modules/.cache
      && chmod -R 777 /app/node_modules/.cache
      && npm run build
      && npm install -g serve
      && serve -s build"
    labels:
      # Domain
      - "traefik.http.routers.crud.rule=Host(`crud.webnunez.com`)"
      #Certresolver
      - "traefik.http.routers.crud.tls.certresolver=prodcertresolver"